release:
  name_template: "{{ .ProjectName }} v{{ .Version }}"

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: tg-message-sender
    binary: tg-message-sender
    main: ./cmd/tg-message-sender
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: binary
    name_template: '{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'

kos:
  - build: tg-message-sender
    repository: "ghcr.io/sputnik-systems"
    tags:
      - latest
      - "{{ .Tag }}"
    bare: true
    preserve_import_paths: false
    base_import_paths: true
    platforms:
    - linux/amd64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
